### ISSUE TITLE
Benennung des Parameters StationsIDs

### ISSUE THREAD

**Issue by VeitSanner** [bundesAPI/dwd-api#7]
In der Open API Spezifikation wird ein Parameter `stationsIds` bzw. `stationsId` gefordert.

https://github.com/bundesAPI/dwd-api/blob/532c3a97864f7c9f73c20557c94971f5dc47cdb0/openapi.yaml#L11-L27

Laut dem [DWD Stationslexikon](https://www.dwd.de/DE/leistungen/klimadatendeutschland/statliste/statlex_html.html;jsessionid=338BEE830AEF0B16DF6D11F3FFDD57B0.live11041?view=nasPublication&nn=16102) stammen die genannten Beispiele aus der Spalte _Stationskennung_. Wenn man Werte aus der Spalte _StationsID_ verwendet, antwortet die Schnittstelle mit einem leeren JSON Objekt `{}`.

Könnte man in einer neuen API-Version den Parameter in _stationsKennung_ umbenennen?

**Comment by VeitSanner** [comment]
@LilithWittmann, könnte sich bitte jemand das Issue ansehen?

Ich wollte mich vorher abstimmen, bevor ich einen PR aufmache.

**Comment by LilithWittmann** [comment]
> Könnte man in einer neuen API-Version den Parameter in _stationsKennung_ umbenennen?

mach gerne PR auf!
